config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end  
  
  get 'home/welcome'
  get "/about", to: "home#about"

  get "/contact", to: "home#contact_us"

  root to: "home#welcome"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  published_at :date
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Post < ActiveRecord::Base
	has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  username               :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def full_name
  	"#{self.first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :username,
        :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Article.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to article_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome

  end

  def about
  	
  end

  def contact_us
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(posts_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to posts_path
			flash[:notice] = "Your Post has been created"
		else
			flash.now[:error] = "Fill the fields	"
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(posts_params)
			redirect_to posts_path
			flash[:notice] = "Your Post has been updated"
		else
			render :new
			flash[:error] = "Fill the fields	"
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	private

	def posts_params
		params.require(:post).permit(:title, :description, :published_at)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="jumbotron">
  <div class="container">
  	<div class="page-header">
		  <h1>Flapper Blog <small>About</small></h1>
		</div>
		<h3>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</h3>
  </div>
</div>

app/views/home/contact_us.html.erb
<script type="text/javascript">
	function initialize() {
	  var mapProp = {
	    center:new google.maps.LatLng(51.508742, -0.120850),
	    zoom:5,
	    mapTypeId:google.maps.MapTypeId.ROADMAP
	  };
	  var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
			<div class="col-sm-12 col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3><i class="icon-map-marker main-color"></i> Location</h3>
					</div>
					<div class="panel-body">
						<!-- <div class="embed-responsive embed-responsive-16by9"> -->
						  <!-- <iframe class="embed-responsive-item" src="http://www.map-generator.org/b0e8940f-c470-4bcd-b903-a5fbf28936bd/iframe-map.aspx"></iframe> -->
						  <iframe src="http://www.map-generator.org/744c8d2e-0615-4991-ab90-0c41c11ee6bc/iframe-map.aspx" scrolling="no" width="1100px" height="450px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><br><small><a href="http://www.map-generator.org/744c8d2e-0615-4991-ab90-0c41c11ee6bc/large-map.aspx" target="_blank">Open large map<a/></small>
						<!-- </div> -->
					</div>	
			</div>
		</div>
	<hr>
	<div class="row">
		<div class="col-sm-4 col-lg-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3><i class="icon-pushpin main-color"></i> Our office</h3>
				</div>
				<div class="panel-body">
					<address>
					<strong>VERSO, Inc.</strong><br>
					795 Folsom Ave, Suite 600<br>
					San Francisco, CA 94107<br>
					<i class="icon-phone-sign"></i> + 4 (123) 456-7890
					</address>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
				  <h3><i class="icon-time main-color"></i> Business hours</h3>
				</div>
				<div class="panel-body">
					<table class="table table-hover">
					  <thead>
							<tr>
							  
							  <th>Day</th>
							  <th>Time</th>
							</tr>
				  	</thead>
				  	<tbody>
							<tr class="success">
							  <td>Monday</td>
							  <td>9:00 to 18:00</td>
							</tr>
							<tr class="success">
							  <td>Tuesday</td>
							  <td>9:00 to 18:00</td>
							</tr>
							<tr class="success">
							 
							  <td>Wednesday</td>
							  <td>9:00 to 18:00</td>
							</tr>
							<tr class="success">
							 
							  <td>Thursday</td>
							  <td>9:00 to 18:00</td>
							</tr>
							<tr class="success">
							 
							  <td>Friday</td>
							  <td>9:00 to 18:00</td>
							</tr>
							<tr class="warning">
							
							  <td>Saturday</td>
							  <td>9:00 to 14:00</td>
							</tr>
							<tr class="danger">
							
							  <td>Sunday</td>
							  <td>day off</td>
							</tr>
			 	 		</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-sm-8 col-lg-8">
	  
			<div class="panel panel-default">
				<div class="panel-heading">	
					<h3 class="">
						<i class="icon-envelope main-color"></i>
						Feel free to contact us
					</h3>
				<div class="panel-body">
				<!-- CONTACT FORM https://github.com/jonmbake/bootstrap3-contact-form -->
			
				<form role="form" id="feedbackForm">
		      <div class="form-group">
						<input type="text" class="form-control" id="name" name="name" placeholder="Name">
						<span class="help-block" style="display: none;">Please enter your name.</span>
		      </div>
		      <div class="form-group">
						<input type="email" class="form-control" id="email" name="email" placeholder="Email Address">
						<span class="help-block" style="display: none;">Please enter a valid e-mail address.</span>
		      </div>
		      <div class="form-group">
						<textarea rows="10" cols="100" class="form-control" id="message" name="message" placeholder="Message"></textarea>
						<span class="help-block" style="display: none;">Please enter a message.</span>
		      </div>
		      <!-- <img id="captcha" src="library/vender/securimage/securimage_show.php" alt="CAPTCHA Image">
	      	<a href="#" onclick="document.getElementById('captcha').src = 'library/vender/securimage/securimage_show.php?' + Math.random(); return false" class="btn btn-info btn-sm">Show a Different Image</a> -->
		      <br>
		      <div class="form-group" style="margin-top: 10px;">
						<input type="text" class="form-control" name="captcha_code" id="captcha_code" placeholder="For security, please enter the code displayed in the box.">
						<span class="help-block" style="display: none;">Please enter the code displayed within the image.</span>
		      </div>
			      
		      <span class="help-block" style="display: none;">Please enter a the security code.</span>
		      <button type="submit" id="feedbackSubmit" class="btn btn-primary btn-lg" style="display: block; margin-top: 10px;">Send Feedback</button>
		    </form>
			<!-- END CONTACT FORM -->
			</div>
		</div>			
	</div>
</div>

<hr>

<footer>
	<div class="container">
		<div class="row">
			<div class="col-12 col-lg-12">
				<p><a href="http://www.bootstraptor.com" title="bootstrap 3 templates">Bootstraptor.com © Company 2013</a></p>
			</div>
		</div>
	</div>
</footer>
    

app/views/home/welcome.html.erb
<div class="jumbotron text-center">
  <h1>Flapper Blog Application</h1>
  <p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
  <% unless user_signed_in? %>
    <p><a class="btn btn-large btn-success" href="#" target="ext">Register for Free</a></p>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-6">
    <h4>Mobile First</h4>
    <p>Responsive by default, and a clean "flat" design.</p>
    
    <h4>Powerful Grid</h4>
    <p>3 responsive grid sizes to control the grid layout on tiny, small and large displays.</p>
  </div>
  
  <div class="col-lg-6">
    <h4>New Elements</h4>
    <p>New panels, list groups, glyphicons and justified navigation.</p>
    
    <h4>Less Bloat</h4>
    <p>The optimized CSS is in a single file. Glyphicons are now separate.</p>
  </div>
</div>

<hr>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Flapper Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
          
        <% else %>
          <li><%= link_to "Post", posts_path %></li>
        <% end %>
      </ul> 
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li><a href="#" id="header_name"><span class="label label-success"><%= current_user.full_name %></span></a></li>
          <li><img id="header_img" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzE0MHgxNDAKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNTA2Yzk2ODk1MyB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE1MDZjOTY4OTUzIj48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA2MjUiIHk9Ijc0LjUiPjE0MHgxNDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4=" alt="..." class="img-circle"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= edit_user_registration_path %>">Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Sign In</a></li>
          <li><a href="<%= new_user_registration_path %>">Register</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlapperBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js">
	</script>
</head>
<body>

	<%= render partial: "layouts/navigation" %>
	<div class="container">
		<%= render partial: "layouts/messages" %>
		<%= yield %> 
		<!-- Content place holder -->
	</div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<!-- Form Tag -->
<%#= form_tag "" do %>
<%= form_for @post, class: "form-horizontal" do |f| %>
	<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">

      <%= f.text_field :title, class: "form-control" %>

      <!-- For Form Tag -->
      <%#= text_field_tag :title, nil %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>

      <%#= text_area_tag :desccription, nil %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Published at</label>
    <div class="col-sm-10">
      <%= f.date_field :published_at, class: "form-control" %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Publish", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>	

<%= link_to "Back", :back, class: "label label-default" %>

app/views/posts/index.html.erb
<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Posts
          <p class="lead">Write and share your views. <a href="/posts/new" class="btn btn-success">Create</a>  new Post</p>
        </h1>
      </div>
    </div> 
  </div><!-- /cont -->
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12"> 
      <div class="panel">
        <div class="panel-body">
          <% if !@posts.blank? %>
            <% @posts.each do |post| %>    
                <!--/stories-->
        		  <div class="row">    
                <br>
                <div class="col-md-2 col-sm-3 text-center">
                  <a class="story-img" href="#">
                    <img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle">
                  </a>
                </div>
                <div class="col-md-10 col-sm-9">
                  <h3><%= post.title %></h3>
                  <div class="row">
                    <div class="col-xs-9">
                      <p><%= post.description %></p>
                      <p class="lead"><a href="<%= post_path(post.id) %>" class="btn btn-default">Read More</a></p>
                      <p class="pull-right"></p>
                      <ul class="list-inline">
                        <li><a href="#"><%= post.published_at.strftime("%d %B, %Y") if !post.published_at.blank? %></a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a></li>
                      </ul>
                      </div>
                    <div class="col-xs-3"></div>
                  </div>
                  <br><br>
                </div>
              </div>
            <% end %>
            <hr>
            <!--/stories-->
        
            <a href="/" class="btn btn-primary pull-right btnNext">More <i class="glyphicon glyphicon-chevron-right"></i></a>  
          <% else %>
            <div class="alert alert-success" role="alert">There are no <strong>Posts</strong> publish.</div>
          <% end %>
        </div>                                  
      </div>                                        
    </div><!--/col-12-->
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create new Post</h1>

<!-- Form Tag -->
<%#= form_tag "" do %>
<%= form_for @post, class: "form-horizontal" do |f| %>
	<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">

      <%= f.text_field :title, class: "form-control" %>

      <!-- For Form Tag -->
      <%#= text_field_tag :title, nil %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>

      <%#= text_area_tag :desccription, nil %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Published at</label>
    <div class="col-sm-10">
      <%= f.date_field :published_at, class: "form-control" %>
    </div>
  </div>
  <br /><br /><br />
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Publish", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>	

app/views/posts/show.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h2><%= @post.title %></h2>
		Published At: <strong><%= @post.published_at.strftime("%d %B, %Y") if !@post.published_at.blank? %></strong>
	</div>
	<div class="panel-body">
		<%= @post.description %>
		<br /><br />	
		<a href="<%= edit_post_path(@post.id) %>" class="label label-default">Edit this post</a>
	</div>
</div>

<div class="panel panel-success">
	<div class="panel-heading">
		<h2>Comment on this post</h2>
	</div>
	<div class="panel-body">
		<ul class="list-group">
		  <li class="list-group-item">
		  	<span class="commenter-name">Ali Ahmed Wrote:	</span>
		  	<br /> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		  tempor incididunt ut labore et dolore magna aliqua.
		  	<br /><span class="comment-date label label-default">24 Spet, 2015</span></li>
		  <li class="list-group-item">Dapibus ac facilisis in</li>
		  <li class="list-group-item">Morbi leo risus</li>
		  <li class="list-group-item">Porta ac consectetur ac</li>
		  <li class="list-group-item">Vestibulum at eros</li>
		</ul>
		
	</div>
</div>